### ISSUE TITLE
ユーザー登録時にエラーが出る

### ISSUE THREAD

**Issue by Masato-Akizaki** [Masato-Akizaki/time-attack-task#96]
```
NoMethodError (undefined method `new_token' for #<Class:0x00007ff214eefb70>):
  
app/models/user.rb:48:in `create_activation_digest'
app/controllers/users_controller.rb:16:in `create'
```

**Comment by Masato-Akizaki** [comment]
`class << self`なしで、メソッドにselfをつけてなかったことが原因
https://magazine.rubyist.net/articles/0046/0046-SingletonClassForBeginners.html
